apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-go-2pbl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-go-2pbl
    app.kubernetes.io/part-of: my-app-go
  name: sample-go-2pbl
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: sample-go-2pbl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: sample-go-2pbl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-tgornals-tenant/my-app-go/sample-go-2pbl@sha256:8dbcbafca636ce8b7ab7b8a702050b71069b238965eb2060685e2c3921439e8d
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
