apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-go-2pbl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-go-2pbl
    app.kubernetes.io/part-of: my-app-go
  name: sample-go-2pbl
  namespace: rhn-support-tgornals-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: sample-go-2pbl
status:
  loadBalancer: {}
