apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-go-2pbl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-go-2pbl
    app.kubernetes.io/part-of: my-app-go
  name: sample-go-2pblxypl
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: sample-go-2pbl
    weight: null
status: {}
